language: ruby
rvm:
- 2.2.2
cache: bundler
before_script:
- "./bin/rake db:setup"
- psql -U postgres -d sfhomeless -c "create extension postgis"
deploy:
  provider: heroku
  api_key:
    secure: rtrWXDwaJuJuRWvDafsQ9qFlbpOBoTRPX/Is3VR/fwzrm03WF/XZiq8h5wK7q8kTwJSh2k0udwdYielr6rthb6qHO7uztyE0hacjempuB6C+uwMOYaDywg+syEfTd4ZCnPGAd/Sp3SnhRue/jHhhSBu4t9mMyzbaCdwi748dw66wl+8JxJrWRg8uPxaSCONixtw1oeqAgCC+QWOiswpu2zki6167ZZOADx38MWGVjdHJ7IJJlBHSbD6OH8m820FTnfiXleyFvoCoY5DLpGTwwHpFUjlu6tITBo1P4CzUJaSAFCtFG51BTJ/DwyFS+WFYyhAQ9pA+TyEd4UrLzMW1XLLT4ETfB2UMxbDuIhHGokj72MBDp/4vBlIyD0F5WF5zA4k/DcQoqUhRCEWGvl8G1ys7h6BnhC3LOKW6NwQPESNVyC3PAXNjTyBy3cSciR+QHWppjiWGKlxc4q+0lChjvb2ywzQWR9Q2RyAWhmZwyzL2FHN59a88HeloL9xqGNbmRCxto9ZyzUFPhWBUcVj8JNPEzQQlQhCUdBLXZHwWoCjBO9gPgRrTZpFBT2mfyAJTLXqP28ay6+AJBXLzf89dGRND55v6UxUg9L3a3STi0k2wEtK3RsFpl7K2ZhVSPN7mZ9LAD5DxB3kmlQy57RBqQfTX36WK4+M1a0gzVztgjnA=
  app: sfhomeless-api-stage
  on:
    repo: ShelterTech/sfhomeless-api
