default: &default
  adapter:            postgis
  host:               localhost
  schema_search_path: public
  database:           sfhomeless

development:
  <<: *default

test:
  <<: *default
  database: sfhomeless_test

production:
  <<: *default
