swagger: '2.0'
info:
  title: ShelterTech API (work in progress)
  description: Access information about homeless resources
  version: 1.0.0
schemes:
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  /resources:
    parameters:
    - $ref: '#/parameters/deviceId'
    get:
      summary: Fetch list of resources
      description: |
        The Resources endpoint returns a paginated list of resources ordered by
        id. If device id is specified returns the rating of each resource for
        the given device.
      parameters:
        - $ref: '#/parameters/page'
        - $ref: '#/parameters/perPage'
        - name: category_names
          in: query
          description: filter resources by category name
          type: array
          items:
            type: string
        - name: category_ids
          in: query
          description: filter resources by category id
          type: array
          items:
            type: integer
      tags:
        - Resource
      responses:
        '200':
          description: An array of resources
          schema:
            type: object
            properties:
              resources:
                type: array
                items:
                  $ref: '#/definitions/Resource'
              meta:
                $ref: '#/definitions/PaginationMeta'
  '/resources/{id}':
    parameters:
      - name: id
        in: path
        description: ID of resource
        required: true
        type: integer
      - $ref: '#/parameters/deviceId'
    get:
      summary: Fetch resource
      description: Fetches rating of resource by the given device if device id header is specified.
      tags:
        - Resource
      responses:
        '200':
          description: A resource
          schema:
            type: object
            properties:
              resource:
                $ref: '#/definitions/Resource'
  /categories:
    get:
      summary: Fetch list of categories
      description: |
        The categories endpoint returns a list of categories ordered by id
      tags:
        - Category
      responses:
        '200':
          description: An array of categories
          schema:
            type: object
            properties:
              categories:
                type: array
                items:
                  $ref: '#/definitions/Category'
  '/categories/{id}':
    get:
      parameters:
      - name: id
        in: path
        description: ID of category
        required: true
        type: integer
      summary: Fetch category
      tags:
        - Category
      responses:
        '200':
          description: A category
          schema:
            type: object
            properties:
              resource:
                $ref: '#/definitions/Category'
  /ratings:
    parameters:
    - name: DEVICE-ID
      required: true
      in: header
      type: string
      description: Unique device identifier
    get:
      summary: Fetch list of ratings
      description: |
        Fetches list of ratings of resources for the given device.
      tags:
        - Resource
      parameters:
        - $ref: '#/parameters/page'
        - $ref: '#/parameters/perPage'
      responses:
        '200':
          description: An array of resource ratings
          schema:
            type: object
            properties:
              ratings:
                type: array
                items:
                  $ref: '#/definitions/Rating'
              meta:
                $ref: '#/definitions/PaginationMeta'
    post:
      summary: Create new rating
      description: |
        Create a new rating of a resource. Name of rating option must
        correspond to an existing option.
      tags:
        - Resource
      parameters:
        - name: rating
          in: body
          required: true
          schema:
            type: object
            properties:
              rating:
                $ref: '#/definitions/Rating'
      responses:
        '201':
          description: An resource rating
          schema:
            type: object
            properties:
              rating:
                $ref: '#/definitions/Rating'
  '/ratings/{id}':
    parameters:
      - name: id
        in: path
        description: ID of rating
        required: true
        type: integer
      - name: DEVICE-ID
        required: true
        in: header
        type: string
        description: Unique device identifier
    get:
      summary: Fetch rating
      description: |
        Fetches a rating
      tags:
        - Resource
      responses:
        '200':
          description: An resource rating
          schema:
            type: object
            properties:
              rating:
                $ref: '#/definitions/Rating'
    put:
      summary: Update rating
      description: |
        Update a rating
      tags:
        - Resource
      responses:
        '200':
          description: An resource rating
          schema:
            type: object
            properties:
              rating:
                $ref: '#/definitions/Rating'
    delete:
      summary: Delete rating
      description: |
        Deletes a rating
      tags:
        - Resource
      responses:
        '204':
          description: Rating successfully deleted
  /rating_options:
    get:
      summary: Fetch list of rating options
      description: |
        Returns list of rating options
      tags:
        - Resource
      responses:
        '200':
          description: An array of rating options
          schema:
            type: object
            properties:
              rating-options:
                type: array
                items:
                  $ref: '#/definitions/RatingOption'
definitions:
  PaginationMeta:
    properties:
      current_page:
        type: integer
        description: Current page index
      next_page:
        type: "integer"
        description: Next page index
        x-nullable: true
      prev_page:
        type: "integer"
        description: Previous page index
        x-nullable: true
      self_url:
        type: "string"
        description: Current page url
      prev_page_url:
        type: "string"
        description: Previous page url
        x-nullable: true
      next_page_url:
        type: "string"
        description: Next page url
        x-nullable: true
  Resource:
    properties:
      id:
        type: integer
        description: Unique id
      title:
        type: string
        description: Name
      email:
        type: string
        description: Contact email
        x-nullable: true
      website:
        type: string
        description: Website for resource
        x-nullable: true
      summary:
        type: string
        description: Short summary of resource (currently unsanitized)
        x-nullable: true
      content:
        type: string
        description: Full description of resource (currently unsanitized)
        x-nullable: true
      categories:
        type: array
        items:
          $ref: '#/definitions/Category'
      phone_numbers:
        type: array
        items:
          $ref: '#/definitions/PhoneNumber'
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
      resource_images:
        type: array
        items:
          $ref: '#/definitions/ResourceImage'
      rating_counts:
        type: object
        description: |
          Keys represent rating types, values represent the number of ratings
          of that type for the given resource. See /rating_options for a list
          of possible options.
        additionalProperties:
          type: integer
      my_rating:
        description: The rating for the given device if DEVICE-ID is set.
        $ref: '#/definitions/Rating'
  ResourceImage:
    properties:
      id:
        type: integer
        description: Unique id
      caption:
        type: string
        description: Image caption
      photo_content_type:
        type: string
        description: Image content type
      photo_file_size:
        type: integer
        description: Image file size in bytes
      photo_url:
        type: string
        description: URL of image original
      photo_styles:
        type: object
        properties:
          thumbnail:
            description: URL to thumbnail sized image (50x50)
            type: string
          medium:
            description: URL to medium sized image (<200x200)
            type: string
          large:
            description: URL to large sized image (<400x400)
            type: string
  PhoneNumber:
    properties:
      id:
        type: integer
        description: Unique id
      country_code:
        type: integer
        description: Country code (e.g. 1 for US)
      area_code:
        type: integer
        description: Area code
      number:
        type: integer
        description: Local exchange and line number
      extension:
        type: integer
        description: Exchange number
        x-nullable: true
      comment:
        type: string
        description: Metadata about phone number (currently empty)
        x-nullable: true
  Category:
    properties:
      id:
        type: integer
        description: Unique id
      name:
        type: string
        description: Name of category
  Address:
    properties:
      id:
        type: integer
        description: Unique id
        readOnly: true
      full_street_address:
        type: string
        description: Fully normalized street address
        readOnly: true
      street1:
        type: string
        description: First part of street address
      street2:
        type: string
        description: Second part of street address
      city:
        type: string
        description: City part of address
      state:
        type: string
        description: State part of address
      state_code:
        type: string
        description: Short code for state
        readOnly: true
      country:
        type: string
        description: Country of address
      country_code:
        type: string
        description: Short code for country
        readOnly: true
      longitude:
        type: number
        description: Longitude of geocoded address
        readOnly: true
      latitude:
        type: number
        description: Latitude of geocoded address
        readOnly: true
  Rating:
    properties:
      id:
        type: integer
        description: Unique id
        readOnly: true
      device_id:
        type: string
        description: ID of the device that left the rating
      resource_id:
        type: integer
        description: Resource this rating applies to
      rating_option:
        $ref: '#/definitions/RatingOption'
  RatingOption:
    properties:
      name:
        type: string
        description: Name of option
parameters:
  page:
    name: page
    in: query
    description: number of page in paginated records (index starting at 1)
    type: integer
  perPage:
    name: per_page
    in: query
    description: records to return per page
    type: integer
  deviceId:
    name: DEVICE-ID
    in: header
    type: string
    description: Unique device identifier
